worked in dd observability stack

diff --git a/.github/workflows/deploy-observability-tools.yaml b/.github/workflows/deploy-observability-tools.yaml
--- a/.github/workflows/deploy-observability-tools.yaml
+++ b/.github/workflows/deploy-observability-tools.yaml
@@ -20,9 +20,10 @@ on:
         type: string
         default: 'deploy' # 'deploy' or 'destroy'
       # Observability stack to deploy
-      # Supported values: datadog, grafana
+      # Supported values: datadog, grafana, dynatrace
       # Grafana stack includes Loki, Tempo, Prometheus, Fluent Bit
       # Datadog stack needs DD_API_KEY secret
+      # Dynatrace stack needs DT_API_TOKEN and optional DT_DATA_INJEST_TOKEN secrets
       observability_stack:
         description: 'Observability stack to deploy'
         required: true
@@ -45,9 +46,12 @@ jobs:
         run: |
 
           if [ "${{ inputs.observability_stack }}" == "datadog" ]; then
-            echo "DECK_CONFIG_OPENTELEMETRY_ENDPOINT=http://datadog-agent.${{ inputs.namespace }}.svc.cluster.local:4318/v1/traces" >> $GITHUB_ENV
+            echo "DECK_CONFIG_OPENTELEMETRY_TRACES_ENDPOINT=http://datadog-agent.${{ inputs.namespace }}.svc.cluster.local:4318/v1/traces" >> $GITHUB_ENV
+          elif [ "${{ inputs.observability_stack }}" == "dynatrace" ]; then
+            echo "DECK_CONFIG_OPENTELEMETRY_TRACES_ENDPOINT=http://collector-kong-collector.opentelemetry-operator-system.svc.cluster.local:4318/v1/traces" >> $GITHUB_ENV
+            echo "DECK_CONFIG_OPENTELEMETRY_LOGS_ENDPOINT=http://collector-kong-collector.opentelemetry-operator-system.svc.cluster.local:4318/v1/logs" >> $GITHUB_ENV
           else
-            echo "DECK_CONFIG_OPENTELEMETRY_ENDPOINT=http://tempo.${{ inputs.namespace }}.svc.cluster.local:4318/v1/traces" >> $GITHUB_ENV
+            echo "DECK_CONFIG_OPENTELEMETRY_TRACES_ENDPOINT=http://tempo.${{ inputs.namespace }}.svc.cluster.local:4318/v1/traces" >> $GITHUB_ENV
           fi
 
       - name: Set up Helm
@@ -69,6 +73,11 @@ jobs:
             cat kong.yaml | deck file add-plugins \
               plugins/datadog.yaml \
               plugins/file-log.yaml \
+              -o kong.yaml
+          elif [ "${{ inputs.observability_stack }}" == "dynatrace" ]; then
+            # ToDo: Add Dynatrace plugins
+            cat kong.yaml | deck file add-plugins \
+              plugins/tcp-log.yaml \
               -o kong.yaml
           else
             cat kong.yaml | deck file add-plugins \
@@ -100,14 +109,43 @@ jobs:
           helm repo add fluent https://fluent.github.io/helm-charts
           helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
           helm repo add datadog https://helm.datadoghq.com
+          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
           helm repo update
 
-      - name: Deploy Prometeus operator
-        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana' }}
-        run: |
-          helm upgrade --install kong-prometheus prometheus-community/kube-prometheus-stack \
-            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/prom/values.yaml
+      #####################################################################
+      ## DYNATRACE STACK DEPLOYMENT                                      ##
+      #####################################################################   
 
+      - name: Deploy Dynatrace OneAgent Operator
+        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'dynatrace'}}
+        run: |
+
+          # Check if the DT_API_TOKEN secret is set
+          if [ -z "${{ secrets.DT_API_TOKEN }}" ]; then
+            echo "DT_API_TOKEN secret is required for Dynatrace OneAgent Operator deployment"
+            exit 1
+          fi
+
+          #Install cert manager
+          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
+
+          kubectl create namespace opentelemetry-operator-system --dry-run=client -o yaml | kubectl apply -f -
+
+          kubectl create secret generic dynatrace-otelcol-dt-api-credentials \
+            --from-literal=DT_ENDPOINT=https://rcr22892.live.dynatrace.com/api/v2/otlp \
+            --from-literal=DT_API_TOKEN=${{ secrets.DT_API_TOKEN }} \
+            -n opentelemetry-operator-system --dry-run=client -o yaml | kubectl apply -f -
+
+          # Create collector service account and role bindings
+          kubectl apply -f ${{ github.workspace }}/k8s/dynatrace/rbac.yaml --dry-run=client -o yaml | kubectl apply -f -
+          
+          kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.116.0/opentelemetry-operator.yaml --dry-run=client -o yaml | kubectl apply -f -
+
+          kubectl apply -f ${{ github.workspace }}/k8s/dynatrace/crd-dynatrace-collector.yaml --dry-run=client -o yaml | kubectl apply -f -
+          # helm upgrade -i dynatrace-collector open-telemetry/opentelemetry-collector \
+          #   -n $DECK_CONFIG_NAMESPACE -f ${{ github.workspace }}/k8s/dynatrace/values.yaml
+      
+      
       #####################################################################
       ## DATADOG STACK DEPLOYMENT                                        ##
       #####################################################################      
@@ -128,6 +166,12 @@ jobs:
       #####################################################################
       ## GRAFANA STACK DEPLOYMENT                                        ##
       #####################################################################
+
+      - name: Deploy Prometeus operator
+        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana' }}
+        run: |
+          helm upgrade --install kong-prometheus prometheus-community/kube-prometheus-stack \
+            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/prom/values.yaml
 
       - name: Create Grafana Kong dashboard ConfigMap
         if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
@@ -152,12 +196,6 @@ jobs:
           helm upgrade --install fluent-bit fluent/fluent-bit \
             -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/fluent-bit/values.yaml
 
-      # - name: Deploy Jaeger
-      #   if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
-      #   run: |
-      #     helm upgrade --install jaeger jaegertracing/jaeger \
-      #       -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/jaeger/values.yaml
-
       ##############################################################################
       ## DESTROY OBSERVABILITY STACK                                              ##
       ##############################################################################
@@ -166,12 +204,18 @@ jobs:
         if: ${{ inputs.action == 'destroy' }}
         run: |
           helm uninstall kong-prometheus -n $DECK_CONFIG_NAMESPACE || true
-          helm uninstall datadog-agent -n $DECK_CONFIG_NAMESPACE || true
           helm uninstall tempo -n $DECK_CONFIG_NAMESPACE || true
           helm uninstall loki -n $DECK_CONFIG_NAMESPACE || true
           helm uninstall fluent-bit -n $DECK_CONFIG_NAMESPACE || true
-          # helm uninstall jaeger -n $DECK_CONFIG_NAMESPACE || true
+          
+          helm uninstall datadog-agent -n $DECK_CONFIG_NAMESPACE || true
           kubectl delete secret datadog-secret || true
+
+          helm uninstall dynatrace-operator -n $DECK_CONFIG_NAMESPACE || true
+          kubectl delete secret dynatrace || true
+
+          kubectl delete -f k8s/dynatrace/crd-dynatrace-collector.yaml || true
+          kubectl delete -f k8s/dynatrace/rbac.yaml || true
 
       - name: Destroy Grafana Kong dashboard ConfigMap
         if: ${{ inputs.action == 'destroy' }}
